### ISSUE TITLE
no issue - thinking of using lustre-data-move...  ...any gotchas or tips?

### ISSUE THREAD

**Issue by scottblomquist** [sdsc/lustre-data-mover#2]
I am considering using to copy a couple of lustre filesystems at MIT.  Any gotchas and/or tips?

Thanks.

**Comment by dimm0** [comment]
Hi,

Read the readme and patch lustreapi.py as described (or get the previous version of the file).

Also celery 4.x requires some changes, I'm going to update sometimes soon. Use 3.x for now or please send the pull request if you update to 4.x yourself. The worker names will be incorrect the way it's written now. Celery 4.x has a benefit of auto retrying sending messages when rabbitmq server is too busy, while 3.x just fails. I didn't see many messages failed during the copy, but it might happen above the rates of 10s of thousands messages/sec - depends on how many workers you're planning to use.

Nothing else I can think of.. Let me know if you have any issues.

**Comment by scottblomquist** [comment]
Thanks!

I commented out the 3 lines in lustreapi.py, brought up rabbitmq and memcached and did start some workers.  I actually tried to just sync a subdir but got the "not a lustre mount" error.  I am going to try the actually filesystem mounts tomorrow.

Also thanks for the tip on celery.  I did just take the default 4.x.  I will roll back to 3.x.

I will be starting with 4 nodes with 16 workers and jumping up to  50 nodes with 16 workers for the final sync while the cluster is down for the final sync.  If the nodes can take more I'll bump them up as much as possible.

**Comment by dimm0** [comment]
You can comment out the checks at https://github.com/sdsc/lustre-data-mover/blob/master/cmover.py#L289 for trying it on folders, but it's really useful for real data copy, since lustre can happen to be unmounted on some workers, which will cause some unwanted effects.

We didn't go above 30 nodes I think, with 16 workers per node, but 50 should be fine depending on your lustre hardware performance. I usually like to start slowly, with 3-5 nodes. Those will scan the first-level folders and put the most load on MDS. In 5 minutes when it's got some files to copy you can start more nodes.

**Comment by dimm0** [comment]
I added the example of our graphite dashboard - something to start with (graphite_dashboard_example.txt file)

**Comment by scottblomquist** [comment]
Thanks, that is really cool.

How do I know that it is "done" or a 1 one complete pass has finished?  When the queue reaches 0? inodes match?  size match?

I started with NEWEST_DATE=0 - Maybe I should have started with a number there?

Thanks for all your help.

**Comment by dimm0** [comment]
When both dirs and files queues reach 0 - the pass is done
When dirs queue reaches 0 - it's not scanning folders anymore, and only copying files

NEWEST_DATE=0 is fine, but it might copy the files which users are actively using.. Frankly I don't know what the effect of that can be. If you have a number there, at least you're not touching the files that were touched by users recently.

**Comment by satra** [comment]
@dimm0 - we are seeing the following pattern during the file copy.

![image](https://cloud.githubusercontent.com/assets/184063/24837837/bfaaed74-1d0a-11e7-8763-61ae5d3b90ab.png)

it looks like there are extended periods where the left graph doesn't change, while the right graph suggests a lot more movement than is evident on the left.  from the left it looks like 3000 files have moved over two hours, while integrating just the lowest curve (pink) on the right would suggest on average (50 files/s x 60 = 3000 files/minute), which would result in a much larger total. 

any thoughts as to the discrepancy?

**Comment by dimm0** [comment]
Left plot shows the number of RabbitMQ messages in the queue. Each message in the files queue contains from one to 1000 files to copy.
Once the dirs worker reaches a folder with, let's say, 100000 files, it would put 100 messages in the queue for the files workers, each containing 1000 files to copy. If files are big enough, you'll see no change in the messages for a while, but big spike in bandwidth and some files copied in the files plot.
The big drops in the messages plot can mean messages with a small number of files processed, for example if a folder contains only 5 files, and there are a bunch of such folders grouped together, you'll see a drop in the number of messages.
You can run `celery -A cmover_control inspect active` to see what workers are working on

**Comment by satra** [comment]
@dimm0 - thank you that's super helpful.

**Comment by satra** [comment]
@dimm0 -  a few more clarification questions. 

on average i'm noticing that about 3500 messages (left plot) are being completed every two hours. given the scale that there are 12.5 million messages (also left plot) this would require for ever it seems (about 300 days).  we had already moved about 300TB, with about 60TB to go. does this check to see if the file is there on the remote node and intact before copying?

can we increase the number of workers on the fly? each of our nodes can support 20 workers.

**Comment by dimm0** [comment]
Again, don't expect any rate to be constant - it depends on the number of files per message and average file size

The RabbitMQ messages only contain the file paths. When file worker gets to the file, it will check if the file is still there (it might be removed since the time it was found by a dir worker - then obviously it's not copied)

Also it's checking whether the file exists on target. If it does, checks the file size, mtime and permissions. If it's different, then removes the target files and copies again, otherwise goes to the next file. The second pass is very fast if nothing was changed on source.

You can increase the number of processes per node by running:
```celery -A cmover_control control pool_grow 2``` - will add 2 processes (workers) per node

**Comment by scottblomquist** [comment]
Thanks for all the help. 

I am not sure I understand celery add_pool and max-concurrency.  When I add more worker processes my max-concurrency stays at 16 (when I inspect stats) but processes does increase.  Do I need to increase max-concurrency too?

Thanks

**Comment by dimm0** [comment]
That's a question to celery developers...
My understanding is max-concurrency affects how many workers are in the beginning, and pool_grow adjusts them during the execution
